<?php

/**
 * Países para seletor de telefone (bandeira emoji + DDI).
 * Brasil primeiro; demais em ordem alfabética (pt-BR).
 */
return [
    ['iso' => 'BR', 'name' => 'Brasil', 'dial' => '55', 'flag' => '🇧🇷'],
    ['iso' => 'DE', 'name' => 'Alemanha', 'dial' => '49', 'flag' => '🇩🇪'],
    ['iso' => 'AO', 'name' => 'Angola', 'dial' => '244', 'flag' => '🇦🇴'],
    ['iso' => 'SA', 'name' => 'Arábia Saudita', 'dial' => '966', 'flag' => '🇸🇦'],
    ['iso' => 'AR', 'name' => 'Argentina', 'dial' => '54', 'flag' => '🇦🇷'],
    ['iso' => 'AU', 'name' => 'Austrália', 'dial' => '61', 'flag' => '🇦🇺'],
    ['iso' => 'BE', 'name' => 'Bélgica', 'dial' => '32', 'flag' => '🇧🇪'],
    ['iso' => 'BO', 'name' => 'Bolívia', 'dial' => '591', 'flag' => '🇧🇴'],
    ['iso' => 'CV', 'name' => 'Cabo Verde', 'dial' => '238', 'flag' => '🇨🇻'],
    ['iso' => 'CA', 'name' => 'Canadá', 'dial' => '1', 'flag' => '🇨🇦'],
    ['iso' => 'CL', 'name' => 'Chile', 'dial' => '56', 'flag' => '🇨🇱'],
    ['iso' => 'CN', 'name' => 'China', 'dial' => '86', 'flag' => '🇨🇳'],
    ['iso' => 'CO', 'name' => 'Colômbia', 'dial' => '57', 'flag' => '🇨🇴'],
    ['iso' => 'KR', 'name' => 'Coreia do Sul', 'dial' => '82', 'flag' => '🇰🇷'],
    ['iso' => 'CR', 'name' => 'Costa Rica', 'dial' => '506', 'flag' => '🇨🇷'],
    ['iso' => 'CU', 'name' => 'Cuba', 'dial' => '53', 'flag' => '🇨🇺'],
    ['iso' => 'DK', 'name' => 'Dinamarca', 'dial' => '45', 'flag' => '🇩🇰'],
    ['iso' => 'AE', 'name' => 'Emirados Árabes Unidos', 'dial' => '971', 'flag' => '🇦🇪'],
    ['iso' => 'EC', 'name' => 'Equador', 'dial' => '593', 'flag' => '🇪🇨'],
    ['iso' => 'ES', 'name' => 'Espanha', 'dial' => '34', 'flag' => '🇪🇸'],
    ['iso' => 'US', 'name' => 'Estados Unidos', 'dial' => '1', 'flag' => '🇺🇸'],
    ['iso' => 'FR', 'name' => 'França', 'dial' => '33', 'flag' => '🇫🇷'],
    ['iso' => 'GH', 'name' => 'Gana', 'dial' => '233', 'flag' => '🇬🇭'],
    ['iso' => 'GT', 'name' => 'Guatemala', 'dial' => '502', 'flag' => '🇬🇹'],
    ['iso' => 'NL', 'name' => 'Holanda', 'dial' => '31', 'flag' => '🇳🇱'],
    ['iso' => 'HN', 'name' => 'Honduras', 'dial' => '504', 'flag' => '🇭🇳'],
    ['iso' => 'IN', 'name' => 'Índia', 'dial' => '91', 'flag' => '🇮🇳'],
    ['iso' => 'IE', 'name' => 'Irlanda', 'dial' => '353', 'flag' => '🇮🇪'],
    ['iso' => 'IT', 'name' => 'Itália', 'dial' => '39', 'flag' => '🇮🇹'],
    ['iso' => 'JP', 'name' => 'Japão', 'dial' => '81', 'flag' => '🇯🇵'],
    ['iso' => 'MX', 'name' => 'México', 'dial' => '52', 'flag' => '🇲🇽'],
    ['iso' => 'MZ', 'name' => 'Moçambique', 'dial' => '258', 'flag' => '🇲🇿'],
    ['iso' => 'NG', 'name' => 'Nigéria', 'dial' => '234', 'flag' => '🇳🇬'],
    ['iso' => 'NO', 'name' => 'Noruega', 'dial' => '47', 'flag' => '🇳🇴'],
    ['iso' => 'NZ', 'name' => 'Nova Zelândia', 'dial' => '64', 'flag' => '🇳🇿'],
    ['iso' => 'PA', 'name' => 'Panamá', 'dial' => '507', 'flag' => '🇵🇦'],
    ['iso' => 'PY', 'name' => 'Paraguai', 'dial' => '595', 'flag' => '🇵🇾'],
    ['iso' => 'PE', 'name' => 'Peru', 'dial' => '51', 'flag' => '🇵🇪'],
    ['iso' => 'PL', 'name' => 'Polônia', 'dial' => '48', 'flag' => '🇵🇱'],
    ['iso' => 'PT', 'name' => 'Portugal', 'dial' => '351', 'flag' => '🇵🇹'],
    ['iso' => 'GB', 'name' => 'Reino Unido', 'dial' => '44', 'flag' => '🇬🇧'],
    ['iso' => 'DO', 'name' => 'República Dominicana', 'dial' => '1', 'flag' => '🇩🇴'],
    ['iso' => 'RU', 'name' => 'Rússia', 'dial' => '7', 'flag' => '🇷🇺'],
    ['iso' => 'SE', 'name' => 'Suécia', 'dial' => '46', 'flag' => '🇸🇪'],
    ['iso' => 'CH', 'name' => 'Suíça', 'dial' => '41', 'flag' => '🇨🇭'],
    ['iso' => 'UY', 'name' => 'Uruguai', 'dial' => '598', 'flag' => '🇺🇾'],
    ['iso' => 'VE', 'name' => 'Venezuela', 'dial' => '58', 'flag' => '🇻🇪'],
];
